#ifndef CONSTANTS_H
#define CONSTANTS_H


#define WHITESPACE          " \n\t"
#define DIGITS              "0987654321"
#define LOWERCASECHARACTERS "abcdefghijklmnopqrstuvwxyz"
#define UPPERCASECHARACTERS "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
#define NONLETTERCHARACTERS "_{}:^;"
#define OPERATIONS          "*-+=[](){}^/|&!~><:;.,@%"
#define LETTERS             LOWERCASECHARACTERS UPPERCASECHARACTERS
#define CHARACTERS          LOWERCASECHARACTERS UPPERCASECHARACTERS NONLETTERCHARACTERS
#define OBJECTCHARACTERS    LOWERCASECHARACTERS UPPERCASECHARACTERS NONLETTERCHARACTERS DIGITS

#endif